//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace balkezesek.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("balkezesek.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to név;első;utolsó;súly;magasság
        ///Jim Abbott;1989-04-08;1999-07-21;200;75
        ///Kyle Abbott;1991-09-10;1996-08-24;200;76
        ///Joel Adamson;1996-04-10;1998-04-26;185;76
        ///Steve Adkins;1990-09-12;1990-10-03;210;78
        ///Juan Agosto;1981-09-07;1993-06-19;190;74
        ///Mike Aldrete;1986-05-28;1996-09-29;180;71
        ///Dana Allison;1991-04-12;1991-05-23;215;75
        ///Beau Allred;1989-09-07;1991-06-25;190;72
        ///Allan Anderson;1986-06-11;1991-10-06;178;71
        ///Eric Anthony;1989-07-28;1997-09-27;195;74
        ///Paul Assenmacher;1986-04-12;1999-10-03;195;75
        ///Oscar A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string balkezesek {
            get {
                return ResourceManager.GetString("balkezesek", resourceCulture);
            }
        }
    }
}
